import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillGithub, AiFillMail} from 'react-icons/ai';
import Image from 'next/image';
import devjuani from '../public/juaniFoto.jpg';
import design from '../public/design.png';
import consulting from '../public/consulting.png';
import code from '../public/code.png';

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio | Juan Ignacio Guerrero</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main className=" bg-slate-100 px-10">
      <section className="min-h-screen">
        <nav className="py-10 mb-12 flex justify-between">
          <h1 className="text-xl font-sans">Mi Portfolio</h1>
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill className="cursor-pointer text-2xl"/>
            </li>
            <li>
              <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
            </li>
          </ul>
        </nav>
        <div className="text-center p-10">
          <h2 className="text-5xl py-2 text-teal-600 font-medium">Juan Ignacio Guerrero</h2>
          <h3 className="text-2xl py-2">Test Automation and Frontend Developer</h3>
          <p className="text-md py-5 leading-8 text-gray-800">
            Estudiante avanzado de licenciatura en Informatica y desarrollo de software en Universidad del Aconcagua, Mendoza, Argentina.
          </p>
        </div>
        <div className="text-5xl flex justify-center gap-16 py-3 text-gray-800">
          <AiFillLinkedin />
          <AiFillGithub />  
          <AiFillMail />
        </div>
        <div className="flex justify-center mt-20 overflow-hidden">
          <Image className="rounded-xl w-80" src={devjuani}/>
        </div>
      </section>
      <section className="flex justify-center items-center flex-col md:flex-row">
  <div className="w-full md:w-1/3 text-center p-4">
    <div className="mb-8">
      <Image src={code} width={100} height={100} className="mx-auto" />
    </div>
    <h3 className="text-lg font-medium pt-8 pb-2">
      Code your dream project
    </h3>
    <p className="py-2">
      Do you have an idea for your next great website? Let's make it a
      reality.
    </p>
    <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
    <p className="text-gray-800 py-1">Photoshop</p>
    <p className="text-gray-800 py-1">Illustrator</p>
    <p className="text-gray-800 py-1">Figma</p>
    <p className="text-gray-800 py-1">Indesign</p>
  </div>
  <div className="w-full md:w-1/3 text-center p-4">
    <div className="mb-8">
      <Image
        src={consulting}
        width={100}
        height={100}
        className="mx-auto"
      />
    </div>
    <h3 className="text-lg font-medium pt-8 pb-2">Consulting</h3>
    <p className="py-2">
      Do you have an idea for your next great website? Let's make it a
      reality.
    </p>
    <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
    <p className="text-gray-800 py-1">Photoshop</p>
    <p className="text-gray-800 py-1">Illustrator</p>
    <p className="text-gray-800 py-1">Figma</p>
    <p className="text-gray-800 py-1">Indesign</p>
  </div>
  <div className="w-full md:w-1/3 text-center p-4">
    <div className="mb-8">
      <Image
        src={design}
        width={100}
        height={100}
        className="mx-auto"
      />
    </div>
    <h3 className="text-lg font-medium pt-8 pb-2">Teaching</h3>
    <p className="py-2">
      Learn how to code from a professional with years of experience.
    </p>
    <h4 className="py-4 text-teal-600">Coding Languages I Teach</h4>
    <p className="text-gray-800 py-1">HTML</p>
    <p className="text-gray-800 py-1">CSS</p>
    <p className="text-gray-800 py-1">JavaScript</p>
    <p className="text-gray-800 py-1">React</p>
  </div>
</section>

     </main>
    </>
  )
}
